import React, { useEffect, useState } from "react";

import Header from "../../components/ui/Header";
import useAuth from "../../hooks/useAuth";

import { getProfile } from "../../services/profileService";
import { getDashboardStats } from "../../services/dashboardService";

import PersonalizedGreeting from "./components/PersonalizedGreeting";
import QuickStatsCard from "./components/QuickStatsCard";
import TrendingContentCard from "./components/TrendingContentCard";
import RecentAchievements from "./components/RecentAchievements";
import QuickActions from "./components/QuickActions";
import LatestWorkoutCard from "./components/LatestWorkoutCard";
import NutritionSummaryCard from "./components/NutritionSummaryCard";
import WeeklyActivityChart from "./components/WeeklyActivityChart";
import AIRecommendationCard from "../../components/ai/AIRecommendationCard";
import { getMLRecommendation } from "../../services/mlRecommendationService";
import { useNavigate } from "react-router-dom";
import { getTodaysWorkout } from "../../services/scheduleService";
import ScheduledWorkoutCard from "./components/ScheduledWorkoutCard";
import { rescheduleWorkout } from "../../services/scheduleService";
import WorkoutCalendar from "./components/WorkoutCalendar";
import { getUpcomingWorkouts } from "../../services/scheduleService";

const quote = {
  text: "Stay strong!",
  author: "FitZone",
};

export default function DashboardHome() {
  const { loading } = useAuth();
  const navigate = useNavigate();

  const [profile, setProfile] = useState(null);
  const [stats, setStats] = useState(null);
  const [recommendation, setRecommendation] = useState(null);
  const [todaysWorkout, setTodaysWorkout] = useState(null);
  const [upcomingWorkouts, setUpcomingWorkouts] = useState([]);



  useEffect(() => {
    async function loadDashboard() {
      try {
        const [profileData, dashboardStats, todayWorkout] = await Promise.all([
          getProfile(),
          getDashboardStats(),
          getTodaysWorkout(),
        ]);

        setProfile(profileData);
        setStats(dashboardStats);
        setTodaysWorkout(todayWorkout);

        const mlResult = await getMLRecommendation(profileData);

        setRecommendation({
          title: "ML-powered recommendation",
          workout: mlResult.recommended_workout,
          reason: "Predicted using your fitness profile and trained machine learning model.",
          confidence: Math.round(mlResult.confidence * 100),
          duration: 45,
          calories: profileData.estimated_calories || 420,
          tips: [
            "This recommendation is generated by a trained ML model.",
            "Track workout completion to improve future predictions.",
            "Consistency improves recommendation quality.",
          ],
        });

        const upcoming = await getUpcomingWorkouts();
        setUpcomingWorkouts(upcoming);
      } catch (err) {
        console.error(err);
      }
    }

    loadDashboard();
  }, []);

  const handleStartAIWorkout = async () => {
    try {
      const mlResult = await getMLRecommendation(profile);

      navigate("/ai-workout-preview", {
        state: {
          aiWorkout: {
            recommendation: {
              confidence: Math.round(mlResult.confidence * 100),
              recovery: "Good",
              reasons: [
                `ML predicted: ${mlResult.recommended_workout}`,
                "Based on your goal and activity level",
                "Personalized from fitness profile features",
              ],
              tips: [
                "Warm up properly",
                "Focus on progressive overload",
                "Recover well after training",
              ],
            },
            workout: {
              title: mlResult.recommended_workout,
              duration: 45,
              calories: profile.estimated_calories || 420,
              exercises: [],
            },
          },
        },
      });
    } catch (error) {
      console.error(error);
      alert("Failed to generate ML recommendation.");
    }
  };


  const handleRescheduleWorkout = async () => {
    if (!todaysWorkout) return;

    const newDate = prompt(
      "Enter new date (YYYY-MM-DD)",
      todaysWorkout.scheduled_date
    );

    if (!newDate) return;

    try {
      await rescheduleWorkout(todaysWorkout.id, newDate);

      setTodaysWorkout({
        ...todaysWorkout,
        scheduled_date: newDate,
      });

      alert("Workout rescheduled successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to reschedule workout");
    }
  };

  const quickStats = {
    weeklyWorkouts: stats?.totalWorkouts ?? 0,
    weeklyTarget: 5,

    totalMinutes: stats?.totalMinutes ?? 0,
    minutesTarget: 300,

    caloriesBurned: stats?.totalCalories ?? 0,
    caloriesTarget: 2000,

    level: profile?.level ?? 1,
  };

  if (!profile || !stats) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center text-white">
        Loading dashboard...
      </div>
    );
  }

  if (!profile || !stats) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center text-white">
        Loading dashboard...
      </div>
    );
  }

  const aiRecommendation = {
    title: "Today's AI Recommendation",

    workout:
  profile?.goal === "Build Muscle"
    ? "Upper Body Strength"
    : profile?.goal === "Weight Loss"
      ? "HIIT Fat Burner"
      : "Full Body Workout",

    reason: `Based on your goal (${profile?.goal ?? "General Fitness"}), activity level (${profile?.activity_level ?? "Intermediate"}), and workout history.`,

    confidence: recommendation?.confidence ?? 94,

    duration: 45,

    calories: profile?.estimated_calories ?? 420,

    tips: recommendation?.tips ?? [
      "Warm up for 5 minutes.",
      "Stay hydrated throughout the workout.",
      "Maintain proper form.",
      "Stretch after finishing.",
    ],
  };
  return (
    <div className="min-h-screen bg-background">
      <Header user={profile} />

      <main className="max-w-screen-2xl mx-auto px-6 py-6 space-y-6">

        {/* Greeting */}
        <PersonalizedGreeting
          user={profile}
          streak={profile.streak ?? 0}
          motivationalQuote={quote}
        />

        {todaysWorkout && (
          <div className="bg-card border border-border rounded-3xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-primary font-medium mb-2">
                  Today's scheduled workout
                </p>
                <h2 className="text-2xl font-bold">
                  {todaysWorkout.routines.name}
                </h2>
                <p className="text-muted-foreground mt-1">
                  Scheduled for today
                </p>
              </div>

              <button
                onClick={() => navigate(`/routine/${todaysWorkout.routine_id}`)}
                className="px-5 py-3 rounded-xl bg-primary text-white font-semibold hover:scale-105 transition"
              >
                View workout
              </button>
            </div>
          </div>
        )}

        <WorkoutCalendar workouts={upcomingWorkouts} />

        <AIRecommendationCard
          recommendation={recommendation}
          onStartAIWorkout={handleStartAIWorkout}
          onBuildOwnWorkout={() => navigate("/exercise-catalog")}
        />

        {/* Stats */}
        <QuickStatsCard stats={quickStats} />

        {/* Continue Workout + Latest Workout */}
        <div className="grid lg:grid-cols-2 gap-6">

          <TrendingContentCard
            routine={stats.activeRoutine}
          />

          <LatestWorkoutCard
            workout={stats.latestWorkout}
          />

        </div>

        <ScheduledWorkoutCard
          workout={todaysWorkout}
          onStart={() =>
            navigate('/workout-session', {
              state: {
                routineId: todaysWorkout.routine_id,
                scheduledWorkoutId: todaysWorkout.id,
              },
            })
          }
          onReschedule={handleRescheduleWorkout}
        />

        {/* Achievements + Nutrition */}
        <div className="grid lg:grid-cols-2 gap-6">

          <RecentAchievements
            achievements={stats.achievements.map((a) => ({
              id: a.id,
              title: a.achievement_name,
              description: "Achievement unlocked!",
              type: "workout",
              earnedAt: a.unlocked_at,
              points: 100,
            }))}
          />

          <NutritionSummaryCard
            stats={stats}
          />

        </div>

        {/* Weekly Activity */}
        <WeeklyActivityChart
          data={stats.weeklyActivity}
        />

        {/* Quick Actions */}
        <QuickActions
          user={profile}
          onQuickStart={() => alert("Workout Started")}
        />

        <AIRecommendationCard
          recommendation={recommendation}
          onStartAIWorkout={handleStartAIWorkout}
          onBuildOwnWorkout={() => navigate("/routines")}
        />

      </main>
    </div>
  );
}